--option 1--
SELECT 
SUM_AMOUNT,DOCTYPE
FROM
(
 SELECT 
 DT.DOCTYPE,CD.SUM(AMOUNT) AS SUM_AMOUNT
 FROM
 CountryDocumetns AS CD
 JOIN
 DocumentTypes AS DT
 ON
 CD.DOCID=DT.DOCID
 GROUP BY DT.DOCTYPE
) AS SUM_DOC
ORDER BY 
SUM_AMOUNT DESC
LIMIT 1 OFFSET 1

--option 2--
SELECT
TOP 1 DOC_AMOUNT.SUM_AMOUNT,DT.DOCTYPE
FROM 
(
  SELECT
  TOP 2 SUM(AMOUNT) AS SUM_AMOUNT,DOCID 
  FROM
   CountryDocumetns 
  GROUP BY 
    DOCID 
  ORDER BY 
  SUM_AMOUNT DESC
) AS DOC_AMOUNT
JOIN
DocumentTypes AS DT 
ON
DOC_AMOUNT.DOCID=DT.DOCID 
ORDER BY 
DOC_AMOUNT.SUM_AMOUNT ASC
